// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {backend} from '../models';

export function ExtractAbstractIDsAndCSRFFromFile(arg1:string):Promise<Array<string>>;

export function ExtractAbstractIDsAndCSRFFromHTML(arg1:string):Promise<Array<string>>;

export function FetchAbstractsData(arg1:context.Context,arg2:Array<string>,arg3:string):Promise<Record<string, any>>;

export function GetAbstractData():Promise<Array<backend.AbstractData>>;

export function GetAbstractIDsAndCSRFFromList(arg1:context.Context):Promise<Array<string>>;

export function GetContributionByID(arg1:string):Promise<backend.ContributionData>;

export function GetContributionData():Promise<Array<backend.ContributionData>>;

export function GetContributionsBySession(arg1:string):Promise<Array<backend.ContributionData>>;

export function GetContributionsByTrack(arg1:string):Promise<Array<backend.ContributionData>>;

export function GetContributionsByType(arg1:string):Promise<Array<backend.ContributionData>>;

export function GetEventInfo(arg1:context.Context,arg2:string):Promise<backend.Event>;

export function ListAbstracts(arg1:context.Context):Promise<string>;
