// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractAbstractIDsAndCSRFFromFile(arg1) {
  return window['go']['backend']['IndicoClient']['ExtractAbstractIDsAndCSRFFromFile'](arg1);
}

export function ExtractAbstractIDsAndCSRFFromHTML(arg1) {
  return window['go']['backend']['IndicoClient']['ExtractAbstractIDsAndCSRFFromHTML'](arg1);
}

export function FetchAbstractsData(arg1, arg2, arg3) {
  return window['go']['backend']['IndicoClient']['FetchAbstractsData'](arg1, arg2, arg3);
}

export function GetAbstractData() {
  return window['go']['backend']['IndicoClient']['GetAbstractData']();
}

export function GetAbstractIDsAndCSRFFromList(arg1) {
  return window['go']['backend']['IndicoClient']['GetAbstractIDsAndCSRFFromList'](arg1);
}

export function GetContributionData() {
  return window['go']['backend']['IndicoClient']['GetContributionData']();
}

export function GetEventInfo(arg1, arg2) {
  return window['go']['backend']['IndicoClient']['GetEventInfo'](arg1, arg2);
}

export function ListAbstracts(arg1) {
  return window['go']['backend']['IndicoClient']['ListAbstracts'](arg1);
}
