data-source:
    use: IPAC27
cache:
    ttl: 24h
    max_size: 100MB
api-tokens:
    - name: jacow-<username>
      base_url: https://indico.jacow.org
      username: <username>
      token: ""
chart-settings:
    excluded_words:
        - example
        - test
        - placeholder
    affiliation_map:
        - canonical: MIT
          aliases:
            - Massachusetts Institute of Technology
            - MIT, USA
          enabled: true
        - canonical: Facility for Rare Isotope Beams
          aliases:
            - Facility for Rare Isotope Beams, Michigan State University
          enabled: true
        - canonical: Brookhaven National Laboratory
          aliases:
            - Brookhaven National Laboratory (BNL)
          enabled: true
        - canonical: CERN
          aliases:
            - European Organization for Nuclear Research
            - European Organization for Nuclear Research (CERN)
          enabled: true
        - canonical: Euclid
          aliases:
            - Euclid Beamlabs LLC
            - Euclid Beamlabs, LLC
            - Euclid TechLabs, LLC
          enabled: true
        - canonical: RadiaBeam
          aliases:
            - RadiaBeam Technologies
          enabled: true
        - canonical: Paul Scherrer Institute
          aliases:
            - Paul Scherrer Institut
          enabled: true
        - canonical: Karlsruhe Institute of Technology
          aliases:
            - Karlsruhe Institute of Technology (KIT)
            - Karlsruhe Instutute of Technology
          enabled: true
        - canonical: Helmholtz-Zentrum Berlin für Materialien und Energie
          aliases:
            - Helmholtz-Zentrum Berlin fuer Materialien und Energie GmbH
            - Helmholtz-Zentrum Berlin für Materialien und Energie
            - Helmholtz-Zentrum Berlin für Materialien und Energie GmbH
          enabled: true
        - canonical: Cornell University
          aliases:
            - Cornell University (CLASSE)
          enabled: true
        - canonical: Technische Universität Darmstadt
          aliases:
            - Technische Universitaet Darmstadt
            - Technische Universität Darmstadt
          enabled: true
        - canonical: TRIUMF
          aliases:
            - University of British Columbia & TRIUMF
          enabled: true
        - canonical: Stony Brook University
          aliases:
            - State University of New York at Stony Brook
          enabled: true
        - canonical: Istituto Nazionale di Fisica Nucleare
          aliases:
            - Istituto Nazionale di Fisica Nucleare - Sez. Roma 1
          enabled: true
        - canonical: Thomas Jefferson National Accelerator Facility
          aliases:
            - Jefferson Lab
          enabled: true
        - canonical: Universitaet Bonn
          aliases:
            - Bonn University
          enabled: true
        - canonical: KEK
          aliases:
            - Sokendai, the Graduate University for Advanced Studies
            - High Energy Accelerator Research Organization
          enabled: true
IPAC27:
    api_token_name: jacow-<username>
    base_url: https://indico.jacow.org
    event_id: 109
    favorite: false
    indico: true
    timeout: 60s