// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function FilterAbstractsByState(arg1:string):Promise<Array<backend.AbstractData>>;

export function FilterContributionsBySession(arg1:string):Promise<Array<backend.ContributionData>>;

export function FilterContributionsByTrack(arg1:string):Promise<Array<backend.ContributionData>>;

export function GetAbstractByID(arg1:number):Promise<backend.AbstractData>;

export function GetAbstracts():Promise<Array<backend.AbstractData>>;

export function GetContributionByID(arg1:string):Promise<backend.ContributionData>;

export function GetContributions():Promise<Array<backend.ContributionData>>;

export function GetEventInfo():Promise<backend.Event>;
