// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyConfigYAML(arg1) {
  return window['go']['main']['App']['ApplyConfigYAML'](arg1);
}

export function ApplyStructuredConfigUI(arg1) {
  return window['go']['main']['App']['ApplyStructuredConfigUI'](arg1);
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function DeleteCacheEntry(arg1) {
  return window['go']['main']['App']['DeleteCacheEntry'](arg1);
}

export function DetermineConfigPath(arg1) {
  return window['go']['main']['App']['DetermineConfigPath'](arg1);
}

export function GetAbstractByID(arg1) {
  return window['go']['main']['App']['GetAbstractByID'](arg1);
}

export function GetAbstracts() {
  return window['go']['main']['App']['GetAbstracts']();
}

export function GetAbstractsByState(arg1) {
  return window['go']['main']['App']['GetAbstractsByState'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCacheEntries() {
  return window['go']['main']['App']['GetCacheEntries']();
}

export function GetCacheKeys() {
  return window['go']['main']['App']['GetCacheKeys']();
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetConfigYAML() {
  return window['go']['main']['App']['GetConfigYAML']();
}

export function GetContributionByID(arg1) {
  return window['go']['main']['App']['GetContributionByID'](arg1);
}

export function GetContributions() {
  return window['go']['main']['App']['GetContributions']();
}

export function GetContributionsBySession(arg1) {
  return window['go']['main']['App']['GetContributionsBySession'](arg1);
}

export function GetContributionsByTrack(arg1) {
  return window['go']['main']['App']['GetContributionsByTrack'](arg1);
}

export function GetEventInfo() {
  return window['go']['main']['App']['GetEventInfo']();
}

export function GetStructuredConfigUI() {
  return window['go']['main']['App']['GetStructuredConfigUI']();
}

export function IsTestMode() {
  return window['go']['main']['App']['IsTestMode']();
}

export function RefreshCache(arg1) {
  return window['go']['main']['App']['RefreshCache'](arg1);
}
