// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {main} from '../models';

export function ApplyConfigYAML(arg1:string):Promise<void>;

export function ApplyStructuredConfigUI(arg1:backend.ConfigDataUI):Promise<void>;

export function ClearCache():Promise<void>;

export function GetAbstractByID(arg1:number):Promise<backend.AbstractData>;

export function GetAbstracts():Promise<Array<backend.AbstractData>>;

export function GetAbstractsByState(arg1:string):Promise<Array<backend.AbstractData>>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetCacheEntries():Promise<Array<backend.CacheEntry>>;

export function GetCacheKeys():Promise<Array<string>>;

export function GetCacheStats():Promise<Record<string, any>>;

export function GetConfigPath():Promise<backend.ConfigPathInfo>;

export function GetConfigYAML():Promise<string>;

export function GetContributionByID(arg1:string):Promise<backend.ContributionData>;

export function GetContributions():Promise<Array<backend.ContributionData>>;

export function GetContributionsBySession(arg1:string):Promise<Array<backend.ContributionData>>;

export function GetContributionsByTrack(arg1:string):Promise<Array<backend.ContributionData>>;

export function GetEventInfo():Promise<backend.Event>;

export function GetStructuredConfigUI():Promise<backend.ConfigDataUI>;

export function IsTestMode():Promise<boolean>;

export function RefreshCache(arg1:string):Promise<void>;
