// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAbstractByID(arg1) {
  return window['go']['main']['App']['GetAbstractByID'](arg1);
}

export function GetAbstracts() {
  return window['go']['main']['App']['GetAbstracts']();
}

export function GetAbstractsByState(arg1) {
  return window['go']['main']['App']['GetAbstractsByState'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetContributionByID(arg1) {
  return window['go']['main']['App']['GetContributionByID'](arg1);
}

export function GetContributions() {
  return window['go']['main']['App']['GetContributions']();
}

export function GetContributionsBySession(arg1) {
  return window['go']['main']['App']['GetContributionsBySession'](arg1);
}

export function GetContributionsByTrack(arg1) {
  return window['go']['main']['App']['GetContributionsByTrack'](arg1);
}

export function GetEventInfo() {
  return window['go']['main']['App']['GetEventInfo']();
}
