// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilterAbstractsByState(arg1) {
  return window['go']['main']['App']['FilterAbstractsByState'](arg1);
}

export function FilterContributionsBySession(arg1) {
  return window['go']['main']['App']['FilterContributionsBySession'](arg1);
}

export function FilterContributionsByTrack(arg1) {
  return window['go']['main']['App']['FilterContributionsByTrack'](arg1);
}

export function GetAbstractByID(arg1) {
  return window['go']['main']['App']['GetAbstractByID'](arg1);
}

export function GetAbstracts() {
  return window['go']['main']['App']['GetAbstracts']();
}

export function GetContributionByID(arg1) {
  return window['go']['main']['App']['GetContributionByID'](arg1);
}

export function GetContributions() {
  return window['go']['main']['App']['GetContributions']();
}

export function GetEventInfo() {
  return window['go']['main']['App']['GetEventInfo']();
}
